### ISSUE TITLE
Segmentation Fault with BlueZ 5.50 on Raspberry Pi OS

### ISSUE THREAD

**Issue by bchwtz** [aykevl/pynus#3]
I am running the latest Raspberry Pi OS on a RPi 3B with BlueZ 5.50 and cannot get your pynus running. Any idea what could be done to fix this would be highly appreciated.

```
root@raspberrypi:/home/pi/pynus# python3 pynus.py 
Connecting to Ruuvi 42AB (E3:F1:A7:E1:42:AB)...
Segmentation fault
```

When executed as normal user without sudo I get:

```

pi@raspberrypi:~/pynus $ python3 pynus.py 
Connecting to Ruuvi 42AB (E3:F1:A7:E1:42:AB)...
Traceback (most recent call last):
  File "/home/pi/pynus/tealblue.py", line 392, in callback_wrapper
    callback(*args)
  File "pynus.py", line 56, in nus
    device.connect()
  File "/home/pi/pynus/tealblue.py", line 176, in connect
    self._device.Connect()
  File "/home/pi/.local/lib/python3.7/site-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/home/pi/.local/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by aykevl** [comment]
This is likely a bug in one of the dependencies, for example the dbus library or the GLib bindings.

Unfortunately I'm not working on this library anymore.
